# Site settings
title: Grayscale
email: matthew.marsicano5@icloud.com
url: https://matthew-marsicano.github.io
description: "Matthew Marsicano, Embedded Software Engineer, Personal Website to highlight projects, experience, and qualifications."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/matthewmarsicano/
  - title: github
    url: https://github.com/Matthew-Marsicano

# Build settings
markdown: kramdown
permalink: pretty
